export const exoLaffay = [
  {
    code: "A1",
    nom: "Pompes genoux",
    type: "poids_de_corps",
    groupe_musculaire_principal: "pectoraux",
    groupes_musculaires_secondaires: ["triceps", "epaules_ant"],
    description_courte: "Pompes avec genoux au sol pour débutants",
    materiel: [],
    avec_charge: false,
  },
  {
    code: "A2",
    nom: "Pompes standard",
    type: "poids_de_corps",
    groupe_musculaire_principal: "pectoraux",
    groupes_musculaires_secondaires: ["triceps", "epaules_ant"],
    description_courte: "Pompes classiques bras tendus",
    materiel: [],
    avec_charge: false,
  },
  {
    code: "A3",
    nom: "Pompes diamant",
    type: "poids_de_corps",
    groupe_musculaire_principal: "triceps",
    groupes_musculaires_secondaires: ["pectoraux", "epaules"],
    description_courte: "Pompes mains jointes sous poitrine",
    materiel: [],
    avec_charge: false,
  },
  {
    code: "A4",
    nom: "Pompes écartées",
    type: "poids_de_corps",
    groupe_musculaire_principal: "pectoraux",
    groupes_musculaires_secondaires: ["triceps", "epaules"],
    description_courte: "Pompes mains larges",
    materiel: [],
    avec_charge: false,
  },
  {
    code: "B1",
    nom: "Tractions supination",
    type: "poids_de_corps",
    groupe_musculaire_principal: "grand_dorsal",
    groupes_musculaires_secondaires: ["biceps", "avant_bras"],
    description_courte: "Tractions paumes vers soi",
    materiel: ["barre_tractions"],
    avec_charge: false,
  },
  {
    code: "B2",
    nom: "Tractions pronation",
    type: "poids_de_corps",
    groupe_musculaire_principal: "grand_dorsal",
    groupes_musculaires_secondaires: ["biceps"],
    description_courte: "Tractions paumes vers l'avant",
    materiel: ["barre_tractions"],
    avec_charge: false,
  },
  {
    code: "C1",
    nom: "Dips chaises",
    type: "poids_de_corps",
    groupe_musculaire_principal: "triceps",
    groupes_musculaires_secondaires: ["pectoraux_inf", "epaules"],
    description_courte: "Dips entre deux chaises",
    materiel: ["deux_chaises"],
    avec_charge: false,
  },
  {
    code: "C2",
    nom: "Dips parallèles",
    type: "poids_de_corps",
    groupe_musculaire_principal: "triceps",
    groupes_musculaires_secondaires: ["pectoraux"],
    description_courte: "Dips sur barres parallèles",
    materiel: ["paralleles"],
    avec_charge: false,
  },
  {
    code: "D",
    nom: "Relevés mollets",
    type: "poids_de_corps",
    groupe_musculaire_principal: "mollets",
    groupes_musculaires_secondaires: [],
    description_courte: "Montée sur pointes de pieds",
    materiel: [],
    avec_charge: false,
  },
  {
    code: "E1",
    nom: "Fentes avant",
    type: "poids_de_corps",
    groupe_musculaire_principal: "quadriceps",
    groupes_musculaires_secondaires: ["fessiers"],
    description_courte: "Grandes fentes alternées",
    materiel: [],
    avec_charge: false,
  },
  {
    code: "F",
    nom: "Pont fessier",
    type: "poids_de_corps",
    groupe_musculaire_principal: "ischio_jambiers",
    groupes_musculaires_secondaires: ["fessiers"],
    description_courte: "Pont dos relevé pieds au sol",
    materiel: [],
    avec_charge: false,
  },
  {
    code: "G",
    nom: "Crunchs abdos",
    type: "poids_de_corps",
    groupe_musculaire_principal: "abdominaux",
    groupes_musculaires_secondaires: ["obliques"],
    description_courte: "Relevés buste au sol",
    materiel: [],
    avec_charge: false,
  },
  {
    code: "H",
    nom: "Pike push-ups",
    type: "poids_de_corps",
    groupe_musculaire_principal: "epaules",
    groupes_musculaires_secondaires: ["triceps"],
    description_courte: "Pompes en V fessier haut",
    materiel: [],
    avec_charge: false,
  },
  {
    code: "K2",
    nom: "Élévations épaules pieds mur",
    type: "poids_de_corps",
    groupe_musculaire_principal: "epaules",
    groupes_musculaires_secondaires: ["triceps"],
    description_courte: "Pieds contre mur bras tendus",
    materiel: ["mur"],
    avec_charge: false,
  },
];
